-- Drop enum if exists (development only)
DO $$ 
BEGIN
   IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'role_enum') THEN
       DROP TYPE role_enum CASCADE;
   END IF;
END$$;

-- Create enum
CREATE TYPE role_enum AS ENUM ('ADMIN', 'USER');

-- Create users table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role role_enum NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (username, email, password, role) 
VALUES ('admin', 'admin@gmail.com', 
        '$2a$10$5XnCWmPZlUOSnW1XKb7rgu16pUmJ.tDX9x4kHdO.Yhf7I/Lg72IhC', 
        'ADMIN');
