INSERT INTO products (name, description, price, stock_qty, image_url, created_at, created_by) VALUES
('Apple iPhone 15', 'Latest Apple smartphone with advanced features', 999.99, 50, 'https://example.com/images/iphone15.jpg', NOW(), 1),
('Samsung Galaxy S24', 'Newest Samsung Galaxy phone with high performance', 899.99, 40, 'https://example.com/images/galaxy_s24.jpg', NOW(), 1),
('Google Pixel 8', 'Google Pixel smartphone with excellent camera', 799.99, 30, 'https://example.com/images/pixel8.jpg', NOW(), 1),
('OnePlus 12', 'High-speed OnePlus smartphone', 699.99, 25, 'https://example.com/images/oneplus12.jpg', NOW(), 1),
('Sony WH-1000XM5', 'Noise-cancelling wireless headphones', 349.99, 60, 'https://example.com/images/sony_wh1000xm5.jpg', NOW(), 1),
('Bose QuietComfort 45', 'Premium wireless headphones with noise cancellation', 329.99, 50, 'https://example.com/images/bose_qc45.jpg', NOW(), 1),
('Dell XPS 13', 'Compact and powerful laptop', 1199.99, 20, 'https://example.com/images/dell_xps13.jpg', NOW(), 1),
('MacBook Pro 16"', 'Apple MacBook Pro with M2 chip', 2499.99, 15, 'https://example.com/images/macbook_pro16.jpg', NOW(), 1),
('HP Spectre x360', 'Convertible 2-in-1 laptop', 1399.99, 18, 'https://example.com/images/hp_spectre_x360.jpg', NOW(), 1),
('iPad Pro 12.9"', 'Apple tablet for professionals', 1099.99, 30, 'https://example.com/images/ipad_pro_12_9.jpg', NOW(), 1),
('Samsung Galaxy Tab S9', 'Samsung premium tablet', 999.99, 25, 'https://example.com/images/galaxy_tab_s9.jpg', NOW(), 1),
('Amazon Kindle Paperwhite', 'E-reader with high-resolution display', 129.99, 100, 'https://example.com/images/kindle_paperwhite.jpg', NOW(), 1),
('Apple Watch Series 9', 'Latest Apple smartwatch', 399.99, 40, 'https://example.com/images/apple_watch9.jpg', NOW(), 1),
('Samsung Galaxy Watch 6', 'Samsung smartwatch with fitness tracking', 349.99, 35, 'https://example.com/images/galaxy_watch6.jpg', NOW(), 1),
('Fitbit Charge 6', 'Fitness tracker with heart rate monitor', 149.99, 60, 'https://example.com/images/fitbit_charge6.jpg', NOW(), 1),
('Canon EOS R6', 'Full-frame mirrorless camera', 2499.99, 10, 'https://example.com/images/canon_eos_r6.jpg', NOW(), 1),
('Nikon Z6 II', 'Mirrorless camera with great low-light performance', 1999.99, 12, 'https://example.com/images/nikon_z6_ii.jpg', NOW(), 1),
('GoPro HERO12', 'Action camera for adventure sports', 499.99, 50, 'https://example.com/images/gopro_hero12.jpg', NOW(), 1),
('DJI Mini 4 Pro', 'Compact drone with 4K camera', 699.99, 20, 'https://example.com/images/dji_mini4_pro.jpg', NOW(), 1),
('Logitech MX Master 3', 'High-precision wireless mouse', 99.99, 80, 'https://example.com/images/logitech_mx_master3.jpg', NOW(), 1),
('Razer BlackWidow V4', 'Mechanical gaming keyboard', 149.99, 40, 'https://example.com/images/razer_blackwidow_v4.jpg', NOW(), 1),
('Samsung SSD 1TB', 'High-speed external SSD storage', 159.99, 70, 'https://example.com/images/samsung_ssd1tb.jpg', NOW(), 1),
('WD My Passport 2TB', 'Portable hard drive', 89.99, 60, 'https://example.com/images/wd_mypassport_2tb.jpg', NOW(), 1),
('Anker PowerCore 26800', 'High-capacity portable charger', 79.99, 100, 'https://example.com/images/anker_powercore_26800.jpg', NOW(), 1),
('Sony PlayStation 5', 'Next-gen gaming console', 499.99, 20, 'https://example.com/images/ps5.jpg', NOW(), 1),
('Xbox Series X', 'Microsoft next-gen console', 499.99, 20, 'https://example.com/images/xbox_series_x.jpg', NOW(), 1);
